### ISSUE TITLE
Please add Honeybadger to your writers wanted list

### ISSUE THREAD

**Issue by starrhorne** [sixhobbits/technical-writing#6]
Hello, 

A helpful person on twitter suggested that we ask you to list us on your writers-wanted list. 

My company is Honeybadger.io. We hire people to do blog posts at $500/post. The posts are usually about larger computing topics as they apply to Ruby development. For example, "Everything about character encoding for Rubyists." We do occasionally feature posts about languages other than ruby. Posts are usually 1500-2500 words and should include code. They don't have to relate to Honeybadger's business of exception monitoring. 

Here's our full write-for-us page: https://www.honeybadger.io/blog/write-for-us/

Thanks!

**Comment by sixhobbits** [comment]
Thanks @starrhorne - added and you can see the details here https://github.com/sixhobbits/technical-writing/blob/master/write-for-us.md
